baseURL = "https://jam.bchari.com/"
languageCode = "ja"
title = "初心者Jamstack"
# theme = "ananke"
hasCJKLanguage = true

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params]
background_color_class = "bg-black"
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
Description = "ブログ初心者が最近流行りのJamstackでブログを作ります！Hugo, Git, Netlifyの登録、設定、使い方などについて書いていきます。"
body_classes = "avenir bg-near-white"
post_content_classes = "avenir bg-near-white"
custom_css = ["css/custom.css"]

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10
